name: build
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get -y install libxml2-utils
        continue-on-error: true
      - run: |
          curl -LO http://www.ftp.ne.jp/Linux/packages/ubuntu/archive/pool/main/libx/libxml2/libxml2-utils_2.9.13+dfsg-1ubuntu0.4_amd64.deb
          if [ -f libxml2-utils_2.9.13+dfsg-1ubuntu0.4_amd64.deb ]; then
            sudo dpkg -i libxml2-utils_2.9.13+dfsg-1ubuntu0.4_amd64.deb
          fi
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test
      - run: cargo build --release
      - run: ./target/release/unofficial-windows-message-center-rss "https://yumetodo.github.io/unofficial-windows-message-center-rss/feed/atom10.xml" > atom10.xml
      - run: xmllint atom10.xml --noout
      - name: Upload Binary
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'
        with:
          name: utf8_to_windows31j_cvt_checker
          path: target/release/unofficial-windows-message-center-rss
          retention-days: 2
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/unofficial-windows-message-center-rss
