name: convert into RSS(ATOM 1.0)
on:
  workflow_dispatch:
  schedule:
    # UTC 表記
    # 日本時間 09:19
    - cron: "19 0 * * *"
jobs:
  scrap:
    runs-on: ubuntu-22.04
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: unofficial-windows-message-center-rss
      - run: chmod +x unofficial-windows-message-center-rss
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages
      - run: ./unofficial-windows-message-center-rss "https://yumetodo.github.io/unofficial-windows-message-center-rss/feed/atom10.xml" > ./pages/feed/atom10.xml
      - name: deploy
        run: |
          cd pages
          git add ./ --all
          git config user.email "yume-wikijp@live.jp"
          git config user.name "yumetodo"
          git commit -a -m "update"
          git push
