name: convert into RSS(ATOM 1.0)
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # UTC 表記
    # 日本時間 09:19
    - cron: "19 0 * * *"
jobs:
  scrap:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: repo
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: pages
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: mkdir -p pages/feed
      - run: cd repo && cargo run > ../pages/feed/atom10.xml
      - name: deploy
        run: |
          cd pages
          git add ./ --all
          git config user.email "yume-wikijp@live.jp"
          git config user.name "yumetodo"
          git commit -a -m "update"
          git push
